### PR TITLE
Added key alias to list of fields available to Prometheus Pump (TT-6127)

### PR DESCRIPTION
**Pull request by nerdydread**
## Description
Key alias is now an available field to populate in custom metrics for Prometheus.

## Related Issue
https://tyktech.atlassian.net/browse/TT-6127 

## Motivation and Context
Client requested functionality.

## How This Has Been Tested
Running both the Tyk Pro Docker Demo and Prometheus locally from my machine, I configured by my tyk-pump instance (running via compiled binary) to utilize custom metrics for Prometheus by adding the following configuration block to the pumps section of my pump.conf.

`"prometheus": {
       "type": "prometheus",
         "meta": {
             "listen_address": "localhost:9999",
             "path": "/metrics",
             "custom_metrics":[
           {
             "name":"tyk_custom_http_status_per_api_name",
             "description":"This is a custom counter",
             "metric_type":"counter",
             "labels":["response_code","api_name", "alias"]
           }
         ]
         }
 }`

I created an API that required an Authorization Token.  I then proceeded to create a key with access to this this api and added an alias to it.  After making a call to the api with the token, I was able to view the alias for the token in the Prometheus metrics.

## Screenshots (if appropriate)
image

Alias from this key is now available in Prometheus metrics.

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additio
[prometheus.zip](https://github.com/TykTechnologies/tyk-pump/files/9245421/prometheus.zip)
ns will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by mativm02** [comment]
I have tested it locally.

Creating a key with a "TestingAlias" alias:
image

After some requests, I checked /metrics and found this:
image

Everything working as expected!

**Review by mativm02 — APPROVED** [review]

**Review by tbuchaillot — CHANGES_REQUESTED** [review]
@mativm02 can we add this new field to the Prometheus section in the [README](https://github.com/TykTechnologies/tyk-pump/blob/e9158ea9839cd9071441b4e663986feead7972b3/README.md#custom-prometheus-metrics) and in the [Labels](https://github.com/TykTechnologies/tyk-pump/blob/e9158ea9839cd9071441b4e663986feead7972b3/pumps/prometheus.go#L60) code comment?

**Comment by mativm02** [comment]
> @mativm02 can we add this new field to the Prometheus section in the [README](https://github.com/TykTechnologies/tyk-pump/blob/e9158ea9839cd9071441b4e663986feead7972b3/README.md#custom-prometheus-metrics) and in the [Labels](https://github.com/TykTechnologies/tyk-pump/blob/e9158ea9839cd9071441b4e663986feead7972b3/pumps/prometheus.go#L60) code comment?

done!

**Review by tbuchaillot — APPROVED** [review]
LGTM

**Pull request merged**
