### PR TITLE
gofmt, goimports, add basic Travis

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by buger** [comment]
I assume you did not meant to gofmt/goimports `vendor` folder?

**Comment by mvdan** [comment]
Did I? I was careful not to. The vendor changes should just be `govendor`.

**Comment by buger** [comment]
Ah, you just added vendored elastic.v5 package 👍

**Comment by mvdan** [comment]
@buger we seem to be green :)

**Pull request merged**
