### PR TITLE
TT5516 avoid double discard of aggregations

### PR DESCRIPTION
**Pull request by sredxny**
## Description
We were discarding and reinitializing the AnalyticsRecordAggregate.APIKeys, first inside `DoAggregatedWriting` and later inside `doMixedWrite`. We should avoid to do it inside `doMixedWrite` because at that point we have the data clean and we dont want to override the information that should be kept

## Related Issue
https://tyktech.atlassian.net/browse/TT-5516

## Motivation and Context
Give solution to https://tyktech.atlassian.net/browse/TT-5516

## How This Has Been Tested
- Create 2 apis protected with token
- Created 2 api keys, once for each api
- Configured 2 aggregation pumps as:
```
 "pumps": {
        "mongo-pump-aggregate-1": {
            "type": "mongo-pump-aggregate",
            "filters":{
                 "api_ids":[],
                 "org_ids":[],
                 "response_codes":[],
                 "skip_api_ids":["6bb2b2a81a3240bf7027339b39372e56"],
                 "skip_org_ids":[],
                 "skip_response_codes":[]
            },
            "meta": {
                "mongo_url": "mongodb://tyk-mongo:27017/tyk_analytics",
                "use_mixed_collection":true
            }
        },
        "mongo-pump-aggregate-2": {
            "type": "mongo-pump-aggregate",
            "filters":{
                             "api_ids":[],
                             "org_ids":[],
                             "response_codes":[200],
                             "skip_api_ids":["e10893e5a3584b5b422531a3ee8a7faf"],
                             "skip_org_ids":[],
                             "skip_response_codes":[]
                        },
            "meta": {
            "ignore_aggregations":["apikeys"],
               "mongo_url": "mongodb://tyk-mongo:27017/tyk_analytics",
               "use_mixed_collection":true
            }
         }
    },
```

replace the api ids, one pump for each api.

- make requests to the first api...you should see information stored in the mongo collection: `tyk_analytics_aggregates` there should be one record with information in the `apikeys` key
- make requests to the second api. The information should be kept and `apikeys` key  should not be empty

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by sredxny** [comment]
@tbuchaillot please check and let me know your toughts....unit test still missing

**Comment by tbuchaillot** [comment]
@sredxny `doMixedWrite ` is only called when `"use_mixed_collection": true,`. In this way, we are just removing the `ignore_aggregations` config.

**Comment by sredxny** [comment]
@tbuchaillot but, previously in `DoAggregatedWriting` we are already ignoring the aggregations. We call that function there as well

**Review by matiasinsaurralde — APPROVED** [review]

**Pull request merged**
