### PR TITLE
[TT-11070]:fix bug where some graphql pumps are not reading env properly

### PR DESCRIPTION
**Pull request by kofoworola**
## Description
This PR fixes a bug that was noticed while making updates to the tyk-pump helm chart, where some Graphql pumps were not initiated with env values that did not use the default env value key.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/780/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7693047105)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/780/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7693047105)

**Review by pvormste — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: d9d64dc3936cc7f554cab31027fa1a84fc4308fd fix bug where some graphql pumps are not reading env properly (#780)
Triggered by: push (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7693494567)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: d9d64dc3936cc7f554cab31027fa1a84fc4308fd fix bug where some graphql pumps are not reading env properly (#780)
Triggered by: push (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7693494567)

**Pull request merged**
