### PR TITLE
[TT-1189] Fix logzio HTTP PROXY proxy (re-vendor to latest master)

### PR DESCRIPTION
**Pull request by buger**
## Description
Logzio can't work with HTTP PROXY env variables.
It was fixed some time ago, so re-vendoring https://github.com/logzio/logzio-go/pull/4

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by tbuchaillot — APPROVED** [review]

**Comment by buger** [comment]
@tbuchaillot can you help with Jira ticket and planning to next release

**Comment by tbuchaillot** [comment]
> @tbuchaillot can you help with Jira ticket and planning to next release

for sure @buger. Can you add some comments on how to test this?

**Comment by buger** [comment]
It require having a trial account at logz.io, and as proxy you can use smth like https://mitmproxy.org/
So when you set HTTP_PROXY=<mitmproxy-addr>, in mitmproxy interface you should see that logz.io doing requests through it.

**Comment by konrad-sol** [comment]
Tested with code from master, status OK

**Pull request merged**
