### PR TITLE
[SYSE-288] tyk-pump/master test-api templates

### PR DESCRIPTION
**Pull request by ermirizio**
The complete list of features for _tyk-pump:master_: releng.

:robot: Beep, boop, this PR has been generated by [automation](https://github.com/TykTechnologies/gromit/blob/master/cmd/policy.go). Changes should be limited to templated code. Where allowed, this PR will be automatically merged when the branch protection rules are satisfied. If you think this was made by mistake, or if merging this might cause any instabilities, please bring it up on Slack or log a jira in the TD project.

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/744/merge
Commit: 5153a0d734af13f401c1d31a94d9ac8c64eafcff 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/6897900451)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/744/merge
Commit: 5153a0d734af13f401c1d31a94d9ac8c64eafcff 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/6897900451)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/744/merge
Commit: 5153a0d734af13f401c1d31a94d9ac8c64eafcff 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/6897900451)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/744/merge
Commit: 5153a0d734af13f401c1d31a94d9ac8c64eafcff 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/6897900451)

**Comment by ermirizio** [comment]
@alephnull this one just needs your approval for merge

**Review by alephnull — APPROVED** [review]

**Pull request merged**
