### PR TITLE
TT-4635 Refactor: Moesif pump converts entity config name to lowercase

### PR DESCRIPTION
**Pull request by keyur9**
Refactor: Moesif Pump converts an entity (user/company) config name to lowercase when fetching an entity (user/company) from the headers

## Description

Earlier/Previous Behavior - 
Moesif pump was not converting an entity (user/company) config name to lowercase but only converting request/response headers to the lowercase which resulted into an entity (user/company) config is not getting fetched when reading from the headers.

This PR changes - 
Moesif Pump converts an entity (user/company) config name to lowercase when fetching an entity (user/company) from the headers. Both headers and config name would be in the lowercase, so will be fetched and logged in Moesif.

## How This Has Been Tested

Setuped Tyk gateway locally, make the moesif pump, build the tyk-pump locally and test moesif pump changes by making api calls via tyk gateway which are captured by Moesif.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [X] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] Check your code additions will not fail linting checks:
  - [X] `go fmt -s`
  - [X] `go vet`

### CODE REVIEW

**Comment by keyur9** [comment]
Hello, @matiasinsaurralde @tbuchaillot! Just wanted to check in - could you review the PR and merge it whenever you've a chance? Let us know if anything else needs to be updated on this PR. Thanks, Keyur

**Comment by tbuchaillot** [comment]
> Hello, @matiasinsaurralde @tbuchaillot! Just wanted to check in - could you review the PR and merge it whenever you've a chance? Let us know if anything else needs to be updated on this PR. Thanks, Keyur

I'll have a look this week @keyur9! thanks for the contribution!

**Review by tbuchaillot — APPROVED** [review]
Looks good! thanks for the contribution @keyur9

**Comment by keyur9** [comment]
Thank you so much for reviewing and merging the PR, @tbuchaillot! 🙏

**Pull request merged**
