### PR TITLE
Updating config comments - v1.9.0 docs

### PR DESCRIPTION
**Pull request by mativm02**
## Description

Updating comments suggested in [this PR.](https://github.com/TykTechnologies/tyk-docs/pull/4114) 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
PR LGTM

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/798/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/8065171331)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/798/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/8065171331)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 328bc732ac43911809309c12b26f2fc71da3b8df Updating config comments - v1.9.0 docs (#798)

* Updating config comments

* linting

* removing debug comment

* Adding all default values for EnvPrefix in BaseMongoConf

* Updating config comments
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/8065471801)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 328bc732ac43911809309c12b26f2fc71da3b8df Updating config comments - v1.9.0 docs (#798)

* Updating config comments

* linting

* removing debug comment

* Adding all default values for EnvPrefix in BaseMongoConf

* Updating config comments
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/8065471801)

**Pull request merged**
