### PR TITLE
[TT-1295] Current log messages are confusing if there was a network error

### PR DESCRIPTION
**Pull request by letzya**
fix https://tyktech.atlassian.net/browse/TT-1295

## Description

We print a message that we wrote X number of records to mongo but actually, we print it before we attempt to write and not after, so in case of problems writing to mongo (network issues, delays, etc. ) we ending up dropping these records completely so I thought we should be clearer about the message - before writing we have a debug level of "attempt to write" and after the write has finished successfully we write an info level message.

I also added the collection name to make it easier to understand errors. 

## Motivation and Context

Per description - to make it easier for our clients to debug issues in tyk-pump, mongo etc.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [X] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by tbuchaillot** [comment]
@letzya, don't you think it would be better if we "normalize" the logs in the way you did for Kafka / Mongo for all the pumps?

**Comment by letzya** [comment]
@tbuchaillot - do you mean - obfuscate for **APIKey** field for unhashed keys? could do but would first check if clients want it.

**Comment by letzya** [comment]
@tbuchaillot that's a great suggestion!

**Comment by letzya** [comment]
closing in favour of @tbuchaillot 's fabulous [PR](https://github.com/TykTechnologies/tyk-pump/pull/319)

**Pull request closed without merging**
