### PR TITLE
TT-2926 Feature/Graceful shutdown

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Adding a mechanism to gracefully shutdown tyk-pump  and adding a `Shutdown` func for all the pumps. 
The only two pumps that do something in that func is `ES`and `dogstatsd` pump, which will flush all the records if bulk config is true.

This feature also implies that on shutdown, tyk-pump is going to wait until the current `purge_loop` cycle finish before ending the process. That means that we will not lose the current processing data on process interrupt/shutdown.

Tyk-pump is going to shut down gracefully on: `os.Interrupt, syscall.SIGINT, syscall.SIGTERM`.
 

## Related Issue

https://tyktech.atlassian.net/browse/TT-2926
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by sredxny — APPROVED** [review]
LGTM! 🚀

**Comment by letzya** [comment]
Looking good. Maybe a few tests?

**Comment by buger** [comment]
I do not  think it should do anything on SIGKILL signal. 
The purpose of this signal is to force process shutdown immediately.

@gwotg any thoughts on it from DevOps point of view?

**Comment by gwotg** [comment]
Think you're right @buger - unless on the parent process, trying to catch or handle sigkill shouldn't work - if we can, this is to be considered an OS bug to be reported (lol). Even so, there isn't much point - if we reached the kill point, let it go - we'll inform the customer on the graceful termination process in the docs (and maybe explicitly inform that sigkill == undefined behavior).

Ref: 
https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html
https://en.wikipedia.org/wiki/Signal_(IPC)#Handling_signals

**Comment by tbuchaillot** [comment]
good catch @buger @gwotg! thanks!

**Comment by tbuchaillot** [comment]
@letzya added a test for this scenario 👍

**Review by matiasinsaurralde — APPROVED** [review]
LGTM

**Review by buger — APPROVED** [review]
👍🏻

**Review by sredxny — APPROVED** [review]
LGTM 🚀

**Pull request merged**
