### PR TITLE
TT-695 Mongo pumps Timeout

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Setting the session timeout for mongo aggregate and selective based on the context.  
This way it could be settable by config.

## Related Issue

https://tyktech.atlassian.net/browse/TT-695

## Motivation and Context

https://tyktech.atlassian.net/browse/TT-695

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by tbuchaillot** [comment]
@gernest @matiasinsaurralde any suggestion on how to handle this in the [normal mongo pump](https://github.com/TykTechnologies/tyk-pump/blob/7b283d8f5df0e8f4a32aae2ac852c4da525e2b53/pumps/mongo.go#L455)? 
IMO it's pretty risky on how we spam go routines and copy sessions in each one.

**Review by gernest — APPROVED** [review]
Looks good to me. Regarding https://github.com/TykTechnologies/tyk-pump/blob/7b283d8f5df0e8f4a32aae2ac852c4da525e2b53/pumps/mongo.go#L455

I don't think we need that goroutine. because `WriteData` is called in a separate goroutine.

**Comment by tbuchaillot** [comment]
> Looks good to me. Regarding
> 
> https://github.com/TykTechnologies/tyk-pump/blob/7b283d8f5df0e8f4a32aae2ac852c4da525e2b53/pumps/mongo.go#L455
> 
> I don't think we need that goroutine. because `WriteData` is called in a separate goroutine.

@gernest Yup, but I'm afraid of that slowing other pumps when purgeLoop takes a big chunk of data since it would mean waiting for a lot of writings.

**Comment by gernest** [comment]
@tbuchaillot can't you maybe batch them? I see we are doing `analyticsCollection.Insert(dataSet...)` . collect `dataSet` and then do a single insert ?.

**Pull request closed without merging**
