### PR TITLE
[TT-10675] Adding AWSToken field for temporary credentials

### PR DESCRIPTION
**Pull request by mativm02**
## Description

When using AWS temporary credentials, a session token is required, so we added this new field within the SQS Pump.
## Related Issue

https://tyktech.atlassian.net/browse/TT-10675?atlOrigin=eyJpIjoiYjI4NTIyNzhiOWJiNGYwODhmNTc0ZDBlNDYzN2Q4YzgiLCJwIjoiaiJ9
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by tbuchaillot — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/790/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7728730974)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: a5e8773b1abad1a424fb5fe3a1ab828be51fa3c8 Adding AWSToken field for temporary credentials (#790)
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7729183332)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: a5e8773b1abad1a424fb5fe3a1ab828be51fa3c8 Adding AWSToken field for temporary credentials (#790)
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7729183332)

**Pull request merged**
