### PR TITLE
[TT-10409] Updating default Mongo driver to mongo-go

### PR DESCRIPTION
**Pull request by mativm02**
## Description

Tyk v3/v4 does not work with MongoDB v5. Before Mongo DB 4.4 will get EOL by Feb 2024, so we are updating our default MongoDB driver to mongo-go from Tyk 5.3.
## Related Issue

https://tyktech.atlassian.net/browse/TT-10409?atlOrigin=eyJpIjoiODdjODE2MTc4M2M1NGRiNmJkZWFhYmNjM2NlMjE1OWUiLCJwIjoiaiJ9
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/783/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7696528510)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/783/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7696528510)

**Review by sredxny — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 956b66a5b981f47507722a37b337deafbea62874 [TT-10409] Updating default Mongo driver to mongo-go (#783)

* Updating default Mongo driver to mongo-go

* fixing TestDefaultDriver test

* fixing TestDefaultDriver test

* updating config comment

* modifying config comment
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7726367553)

**Pull request merged**
