### PR TITLE
Auto generated from templates by gromit

### PR DESCRIPTION
**Pull request by ermirizio**
Changes related to SYSE-288

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: ** :no_entry_sign: 
Branch used: refs/pull/742/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/6868136760)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: ** :no_entry_sign: 
Branch used: refs/pull/742/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/6868136760)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: ** :no_entry_sign: 
Branch used: refs/pull/742/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/6868136760)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: ** :no_entry_sign: 
Branch used: refs/pull/742/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/6868136760)

**Comment by alephnull** [comment]
Slack notification failing.

**Review by alephnull — COMMENTED** [review]
Slack notifications seem to be failing.

**Comment by ermirizio** [comment]
> Slack notifications seem to be failing.

@alephnull don't worry , this was due to SECRET not setup at that time, since I was waiting for konrad to define the channel. Is set now, I did re-run to check everything is working as expected

**Pull request closed without merging**
