### PR TITLE
TT-8761 Fix: Tyk prometheus pump separator issue

### PR DESCRIPTION
**Pull request by kaushal-move**
## Description
In the `Inc` and `Observe` functions, the keys for the counterMap and histogramMap are generated by joining the label values with a double hyphen (--). When the Expose function is called, the keys are split back into label values using the same double hyphen as a separator. The problem occurs because the API name (e.g. test--api-name) or Path (e.g. www.example.com/test/test--123) contains a double hyphen, causing an incorrect split and resulting in a different number of label values than expected.

This causes cardinality error in pump `panic: inconsistent label cardinality: expected 5 label values but got 6` and the pod crashes.

## Related Issue
https://github.com/TykTechnologies/tyk-pump/issues/600

## Motivation and Context
We have a production pump which keeps on crashing due to very same reason

## How This Has Been Tested
Unit tests: added a unit test with the `--` separator

## Screenshots (if appropriate)
test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
Thank you for contribution? 

Is it backward compatible change? E.g. does the prometheus gets data in the same format in the end?

**Comment by patriziobrunops** [comment]
Hi @buger !
Any chance this is going to be released soon?

**Review by tbuchaillot — APPROVED** [review]
Looks good! Thanks for the contribution @kaushal-move 🚀

**Comment by tbuchaillot** [comment]
> Hi @buger ! Any chance this is going to be released soon?

@patriziobrunops @kaushal-move, we are going to include this in Pump 1.8.1 - Planned for the end of May 2023. 

We ported this PR here https://github.com/TykTechnologies/tyk-pump/pull/636 ( we need to make some CI jobs to run). I will close this one but thanks again for the contribution!

**Comment by patriziobrunops** [comment]
@tbuchaillot Hi, is there a new schedule for pump 1.8.1?

**Comment by caroltyk** [comment]
Hi @kaushal-move @patriziobrunops , pump v1.8.1 has been released today. :)

**Pull request closed without merging**
