### PR TITLE
[SYSE-87] test-controller job decides test scope

### PR DESCRIPTION
**Pull request by alephnull**
The complete list of features for _tyk-pump:master_: releng.

:robot: Beep, boop, this PR has been generated by [automation](https://github.com/TykTechnologies/gromit/blob/master/cmd/policy.go). Changes should be limited to templated code. Where allowed, this PR will be automatically merged when the branch protection rules are satisfied. If you think this was made by mistake, or if merging this might cause any instabilities, please bring it up on Slack or log a jira in the TD project.

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/771/merge
Commit: 10fbc3bdc7ab758f42b19ee0fcf62d89421179d6 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7552760255)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/771/merge
Commit: 10fbc3bdc7ab758f42b19ee0fcf62d89421179d6 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7552760255)

**Review by asutosh — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 69e4ac246f8d663da03a156368229286b6ae2d63 Auto generated from templates by gromit (#771)

Co-authored-by: Gromit <policy@gromit>
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7580216762)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 69e4ac246f8d663da03a156368229286b6ae2d63 Auto generated from templates by gromit (#771)

Co-authored-by: Gromit <policy@gromit>
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7580216762)

**Pull request merged**
