### PR TITLE
[TT-2183] Create CSV from AnalyticsRecord without using reflectin

### PR DESCRIPTION
**Pull request by ps258**
## Description
I've implemented the GetFieldNames and GetLineValues without reflection by simply including the details from the structures.

## Related Issue
This is related to a customer support ticket 
https://support.tyk.io/hc/en-gb/requests/11978

## Motivation and Context
GetFieldNames and GetLineValues were first written when AnalyticsRecord a very simple structure. As it's grown they have not been updated to deal with it. As a result the CSV output couldn't handle boolean values or the values stored in the sub-structures within AnalyticsRecord 

## How This Has Been Tested
I've only tested it in my own docker environment. My interest was to scratch an itch and enjoy some recreational coding.
It's worked just fine though
I've tested calling APIs and reading the CSV output. My test setup doesn't populate the GeoData struct so it might be an idea to make sure that bit works

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [x ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x ] Check your code additions will not fail linting checks:
  - [x ] `go fmt -s`
  - [ x] `go vet`

### CODE REVIEW

**Review by tbuchaillot — APPROVED** [review]
LGTM

**Comment by tbuchaillot** [comment]
@ps258 merged and it will be included in our next pump release :) Thanks a lot for the contribution!

**Comment by letzya** [comment]
@ps258 just popping up here to say thanks for the contribution!!!

**Comment by ps258** [comment]
Thanks guys!

**Comment by christtyk** [comment]
@ps258 released in 1.3.0 thanks!

**Pull request merged**
