### PR TITLE
Added omit_detailed_recording configuration

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Fix https://github.com/TykTechnologies/tyk-sink/issues/78

Added `omit_detailed_recording` config option at the root level and in each pump config to avoid writing `raw_request` and `raw_response` fields for each request in pumps.

Root level config has more priority than the pump level config.

Example root level config: 
```
{
  "analytics_storage_config": {
    ....
  },
  "analytics_storage_type": "redis",
  "dont_purge_uptime_data": true,
  "pumps": {
   "csv": {
      "type": "csv",
      "meta": {
        "csv_dir": "csv"
      }
    }
  },
  "purge_delay": 1,
  "omit_detailed_recording": true
}
```
 Example pump level config: 
```
...
  "pumps": {
   "csv": {
      "type": "csv",
      "omit_detailed_recording":true,
      "meta": {
        "csv_dir": "csv"
      }
    }
  },
..
}
```
## Motivation and Context

Mostly to avoid cloud issues.

## How This Has Been Tested

Manually tested with  root level `omit_detailed_recording` config.
Added test to validate the `omit_detailed_recording` at pump level config.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [X] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] Check your code additions will not fail linting checks:
  - [X] `go fmt -s`
  - [X] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
Hmm, I actually think it should be an option on Mongo pump level, and on ES pump level (the only pumps which record detailed data).

**Comment by buger** [comment]
Also reflect this changes on the MDCB too.

**Comment by tbuchaillot** [comment]
> Hmm, I actually think it should be an option on Mongo pump level, and on ES pump level (the only pumps which record detailed data).

@buger although the other pumps don't decode the detailed data, they use it. I think it's a better solution to cut the detailed data in the root.

**Comment by joshblakeley** [comment]
Would be great as a root config variable so can be set via ENV for 12 factor app compliance etc

**Comment by buger** [comment]
@joshblakeley Individual pump configs nowdays can be set via ENV variables too. 

So let's do the config on both the global pump.conf level, and individual pump level. And always prefer using config values to command-line arguments, since as mentioned by @joshblakeley some things like setting value via ENV will not work.

**Comment by tbuchaillot** [comment]
@buger modified to be a configuration option at root level or at the pump level.

**Comment by buger** [comment]
Pls rename the variable to "omit_detailed_recording" so it will match with our gw config variable name

**Comment by tbuchaillot** [comment]
> Pls rename the variable to "omit_detailed_recording" so it will match with our gw config variable name

Done!

**Comment by matiasinsaurralde** [comment]
@tbuchaillot We have a conflict in `pumps/hybrid.go`.

**Comment by matiasinsaurralde** [comment]
Cherry-picked and merged to the release branch: https://github.com/TykTechnologies/tyk-pump/commit/4e5ec57bbe4352b24667ccb7c009dae3f5c9842f
Fixed a compilation error with the syslog pump which didn't originally support the new `CommonPumpConfig`: #280, https://github.com/TykTechnologies/tyk-pump/commit/2ab79f32d59aec95e52d6a64961fabfe341ffd16

**Pull request merged**
