### PR TITLE
TT-5078 Feature/ Prometheus custom metrics

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Added a new feature for Prometheus pump to allow users to create custom metrics.

How does it works?
Now you can add multiple custom_metrics in prometheus meta specifying the type of the metric and which labels / values is it going to use. Docs: https://github.com/TykTechnologies/tyk-pump/tree/feature/prometheus-custom-metrics#custom-prometheus-metrics

Example:
```
"prometheus": {
  "type": "prometheus",
	"meta": {
		"listen_address": "localhost:9090",
		"path": "/metrics",
        "custom_metrics":[
          {
            "name":"tyk_custom_http_status_per_api_name",
            "description":"This is a custom counter",
            "metric_type":"counter",
            "labels":["response_code","api_name"]
          }
        ]
	}
},
```

So in this way, you can aggregate the metrics the way you want and expose them in Prometheus.

## Related Issue

https://tyktech.atlassian.net/browse/TT-5078
## Motivation and Context

https://tyktech.atlassian.net/browse/TT-5078
## How This Has Been Tested

Added some unit tests.

In order to manually test it you need to:
- Set Prometheus pump with the description config.
- run Tyk Pump - send some traffic.
- hit your Prometheus pump /metrics configured endpoint, you should see your custom metric there.
- play  with different custom metric combination.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by sredxny — CHANGES_REQUESTED** [review]
can you add information on how to test it? at first glance the code looks good, but we still need test coverage

**Comment by tbuchaillot** [comment]
> can you add information on how to test it? at first glance the code looks good, but we still need test coverage

@sredxny added testing instructions and some unit tests, let me know what do you think.

**Review by matiasinsaurralde — APPROVED** [review]
LGTM

**Pull request merged**
