### PR TITLE
try new smoke tests workflow

### PR DESCRIPTION
**Pull request by ermirizio**
Decouple smoke tests from release.yml into a reusable workflow

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/749/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7011557649)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/749/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7011557649)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/749/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7011557649)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/749/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7011557649)

**Comment by ermirizio** [comment]
@alephnull , @asutosh  please drop some comments here about this approach and let me know what do you think. The rest of the repositories will take the same approach

**Pull request closed without merging**
