### PR TITLE
Merging to release-1.9: [TT-10673] Upgrading to Go 1.21 (#766)

### PR DESCRIPTION
**Pull request by buger**
[TT-10673] Upgrading to Go 1.21 (#766)

* upgrading to Go 1.21

* fixing loop issue

* removing comment

* linting

* add release 1.19 revert 1.18 req tests

* removing commented linters

* removing 1.19 branch from terraform

---------

Co-authored-by: Esteban Ricardo Mirizio <ermirizio@gmail.com>

[TT-10673]: https://tyktech.atlassian.net/browse/TT-10673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/772/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7556180161)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/772/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7556180161)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/772/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7556180161)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/772/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7556180161)

**Review by asutosh — APPROVED** [review]

**Pull request merged**
