### PR TITLE
Update Moesif pump

### PR DESCRIPTION
**Pull request by keyur9**
## Description

- Added new features to Moesif pump. Sampling events sent to Moesif, option to log request/response body, and mask headers/body. 
- Bump `moesifapi-go` dependency to version v1.0.5.

## How This Has Been Tested

Setuped Tyk gateway locally, make the moesif pump, build the tyk-pump locally and test moesif pump changes by making api calls via tyk gateway which are captured by Moesif.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [x] My change requires a change to the documentation.
  - [] If you've changed APIs, describe what needs to be updated in the documentation.
- [x] I have updated the documentation accordingly.
- [] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by dgilling** [comment]
Was there any status on approving this PR?

**Comment by keyur9** [comment]
Hello @buger/@lonelycode could you share the process of reviewing/approving this PR? I'm not able to add any reviewers to the PR. Please suggest.

**Comment by dgilling** [comment]
Hi @buger @furkansenharputlu @tbuchaillot  and @komalsukhani I just wanted to check if had a chance to review this.

**Comment by matiasinsaurralde** [comment]
Merged to `master` in 3b1d8e7e0dce88576b5d5f9ec1fbf7c28915aa62

**Comment by matiasinsaurralde** [comment]
We plan to include this in our next release, Tyk Pump 1.1.0 👍

**Pull request closed without merging**
