### PR TITLE
Add Mongo SSL support

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Related to #21.

### CODE REVIEW

**Comment by matiasinsaurralde** [comment]
@buger if this approach is ok, I will modify the other Mongo pumps.

**Comment by matiasinsaurralde** [comment]
👍

**Comment by lonelycode** [comment]
Also make sure environment variables still work

**Comment by lonelycode** [comment]
Can we merge this yet?

**Comment by ilijabojanovic** [comment]
@buger verified and approved for merge

**Pull request merged**
