### PR TITLE
[SYSE-170]: Replace pc.sh with packagecloud publish

### PR DESCRIPTION
**Pull request by asutosh**
## Description
This PR  updates the goreleaser config to test SYSE-170, and the implementation of `packagecloud publish`.

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/793/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7786704759)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/793/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7786704759)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v1.9.0-alpha1
Commit: 7b7ee52b8bc947d00d9f793513ec33a0f173028f 
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7798019809)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v1.9.0-alpha1
Commit: 7b7ee52b8bc947d00d9f793513ec33a0f173028f 
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk-pump/actions/runs/7798019809)

**Comment by asutosh** [comment]
Publishing tested using a tag push (https://packagecloud.io/app/tyk/tyk-pump-unstable/search?q=1.9.0~alpha1).
Closing this,  have added this change to the releng templates and it would be updated here during the next  template sync.

**Pull request closed without merging**
