### PR TITLE
Update DogStatsD to support customizable tags

### PR DESCRIPTION
**Pull request by diegobernardes**
There is no option to customize DogStatsD and this may have a negative impact on the billing with tags like `path` that are sent by default.

## Description
This PR adds an option to configure the tags pushed to DogStatsD.

## Motivation and Context
Decrease the cost of Datadog.

## How This Has Been Tested
There are no automated tests for the `dogstatsd.go` file. I did some manual tests and the code works.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [X] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [X] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [X] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] Check your code additions will not fail linting checks:
  - [X] `go fmt -s`
  - [X] `go vet`

### CODE REVIEW

**Comment by matiasinsaurralde** [comment]
Thanks, we'll review it!

**Comment by tbuchaillot** [comment]
@diegobernardes thanks for this PR! 
I think it would be better if we maintain the current behavior by default and if `s.conf.Tags > 0` we use this logic to maintain backward compatibility.

**Comment by diegobernardes** [comment]
@tbuchaillot, done. But I really think that the default values, in this case, are bad. This is the command that is present at the `WriteData` function:
```
From DataDog website:
Tags shouldn’t originate from unbounded sources, such as EPOCH timestamps, user IDs, or request IDs. Doing
so may infinitely increase the number of metrics for your organization and impact your billing.

As such, we have significantly limited the available metrics which gets sent to datadog.
```

And that's exactly the problem, we're sending unbounded information by default with the `path` tag. If the tyk instance is a low volume one, it's ok, but with a high volume instance, it's simply inviable to use datadog due to the cost.

**Comment by buger** [comment]
#Let’s then update default config in docs/readme, and new users will get the change and old will be unaffected

**Comment by diegobernardes** [comment]
@buger, no problem. Readme updated.

**Review by tbuchaillot — APPROVED** [review]

**Comment by konrad-sol** [comment]
Tested on PR branch -> QA status OK

**Pull request merged**
