### PR TITLE
TT-383 support elastic search 7

### PR DESCRIPTION
**Pull request by sredxny**
## Description
Add support to use Elastic Search 7 . Basically the DocumentType is getting deprecated so for ES7 we do not use that field

## Related Issue
https://tyktech.atlassian.net/browse/TT-383

## Motivation and Context
Give native support to ElasticSearch 7 pump with no hacks

## How This Has Been Tested
- Setup environment as:
     -  Create network: `docker network create es`
     - Run ES7: `docker run -it --rm --name elasticsearch --net es -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.14.0`
     - Run Kibana to visualize data: ` docker run -it --rm --name kibana --network es -p 5601:5601 \
  -e ELASTICSEARCH_HOSTS=http://elasticsearch:9200 \
  docker.elastic.co/kibana/kibana:6.8.6
`
- Create ES7 Pump:
```
"elasticsearch": {
            "type": "elasticsearch",
            "meta": {
                "index_name": "tyk_analytics",
                "elasticsearch_url": "http://localhost:9200",
                "enable_sniffing": false,
                "document_type": "tyk_analytics",
                "rolling_index": false,
                "extended_stats": false,
                "version": "7"
            }
        },
```
- Send traffic
- We should see data in kibana
- Test again but removing the key `elasticsearch.meta.document_type` and again, we should see new data in kibana.

**Note:**
I notice  as well the creation of the indexes in Elastic search:
```
{"type": "server", "timestamp": "2021-08-27T20:30:54,864Z", "level": "INFO", "component": "o.e.c.m.MetadataCreateIndexService", "cluster.name": "docker-cluster", "node.name": "c5283ed6a7bd", "message": "[tyk_analytics] creating index, cause [auto(bulk api)], templates [], shards [1]/[1]", "cluster.uuid": "AoM0ym55SkeK9fov9GH8Rw", "node.id": "8yCmv4xyRduiwG7TVlHL-Q" }
{"type": "server", "timestamp": "2021-08-27T20:30:55,017Z", "level": "INFO", "component": "o.e.c.m.MetadataMappingService", "cluster.name": "docker-cluster", "node.name": "c5283ed6a7bd", "message": "[tyk_analytics/tZFRLEvyR7uhasVP4KsZNg] create_mapping [tyk_analytics]", "cluster.uuid": "AoM0ym55SkeK9fov9GH8Rw", "node.id": "8yCmv4xyRduiwG7TVlHL-Q" }
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [x] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by tbuchaillot — APPROVED** [review]
Looks good to me!

**Comment by tbuchaillot** [comment]
@sredxny could you modify the readme adding this version?

**Comment by sredxny** [comment]
@tbuchaillot makes sense, will do so, thanks!

**Comment by sredxny** [comment]
done!

**Pull request merged**
